<a href="https://colab.research.google.com/github/vivianconrad/neural-networks-and-deep-learning/blob/main/Conrad.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Q1: Build a simple neural network

The neural networks contains:
- 6 inputs, 2 hidden layer with 6 nodes

The neural network performs prediction to obtain:
- 6 output values by multiplying inputs with weights.

**Parameters**

- Input layer weight values:

            [0.1, 0.2, 0.9, -0.1, 0.2, 0.1],
            [-0.1, 0.1, 0.78, 0.2, 0.1, 0.9], 
            [-0.1, 0.2, 0.1, 0.1, 0.12, 0.9], 
            [0.1, 0.4, 0.2, 0.1, 0.89, 0.1],
            [-0.1, 0.1, 0.12, 0.2, 0.1, 0.9], 
            [0.1, 0.4, 0.2, 0.1, 0.89, 0.1]

- Hidden layer 1 weight values: 

            [0.3, 0.1, 0.2, 0.1, 0.89, -0.3],
            [0.1, -0.2, 0.2, 0.1, 0.34, 0.0],
            [0.1, 0.2, 0.7, 0.2, 0.1, 0.0],
            [0.1, -0.2, 0.34, 0.2, 0.1, 0.0],
            [0.1, 0.2, 0.2, 0.1, 0.7, 0.1],
            [0.0, -1.3, -0.6, 0.2, 0.1, 0.1]

- Hidden layer 2 weight values: 

            [0.1, 0.1, 0.79,0.2, 0.1, -0.2],
            [0.1, -0.22, 0.47, 0.2, 0.1, 0.2],
            [0.3, 0.12, 0.5, 0.2, 0.1, 0.0],
            [0.1, -0.2, 0.34, 0.2, 0.1, 0.0],
            [0.2, 0.2, 0.2, 0.1, 0.7, 0.1],
            [0.1, -1.3, -0.6, 0.1, 0.2, 0.1]

- Input Values:

  input1 = [88.50]
  
  input2 = [72.95]
  
  input3 = [18.25]
  
  input4 = [0.29]
  
  input5 = [12.69]
  
  input6 = [38.2]


**Expected Outcome**
- [ 37.629953   18.0629716  34.3317195  20.637146   70.034887  -16.620856 ]

In [ ]:
# write your code here
import numpy as np

input_weights = np.array([ 
            [0.1, 0.2, 0.9, -0.1, 0.2, 0.1],
            [-0.1, 0.1, 0.78, 0.2, 0.1, 0.9], 
            [-0.1, 0.2, 0.1, 0.1, 0.12, 0.9], 
            [0.1, 0.4, 0.2, 0.1, 0.89, 0.1],
            [-0.1, 0.1, 0.12, 0.2, 0.1, 0.9], 
            [0.1, 0.4, 0.2, 0.1, 0.89, 0.1]])

hidden_weights_1 = np.array([  
            [0.3, 0.1, 0.2, 0.1, 0.89, -0.3],
            [0.1, -0.2, 0.2, 0.1, 0.34, 0.0],
            [0.1, 0.2, 0.7, 0.2, 0.1, 0.0],
            [0.1, -0.2, 0.34, 0.2, 0.1, 0.0],
            [0.1, 0.2, 0.2, 0.1, 0.7, 0.1],
            [0.0, -1.3, -0.6, 0.2, 0.1, 0.1]])

hidden_weights_2 = np.array([  
            [0.1, 0.1, 0.79,0.2, 0.1, -0.2],
            [0.1, -0.22, 0.47, 0.2, 0.1, 0.2],
            [0.3, 0.12, 0.5, 0.2, 0.1, 0.0],
            [0.1, -0.2, 0.34, 0.2, 0.1, 0.0],
            [0.2, 0.2, 0.2, 0.1, 0.7, 0.1],
            [0.1, -1.3, -0.6, 0.1, 0.2, 0.1]])


weights = [input_weights, hidden_weights_1, hidden_weights_2]

def simple_neural_network(input, weights):
    hidden_layer_1 = input.dot(weights[0])
    hidden_layer_2 = hidden_layer_1.dot(weights[1])
    prediction_layer = hidden_layer_2.dot(weights[2])
    return prediction_layer

    
input1 = np.array([88.50])
input2 = np.array([72.95])
input3 = np.array([18.25])
input4 = np.array([0.29])
input5 = np.array([12.69])
input6 = np.array([38.2])

input = np.array([input1[0],input2[0],input3[0],input4[0], input5[0], input6[0]])
output_prediction = simple_neural_network(input,weights)

print(output_prediction)

[ 37.629953   18.0629716  34.3317195  20.637146   70.034887  -16.620856 ]


## Q2: Write Python code using NumPy that does the following. 

- Create a function called **create_duplicate_array_of_zeros** which accepts **input_array** as a parameter, where input_array is a NumPy array and we will return a NumPy array made up of zeros with the same dimensions.
- The output should be data structure format similar to test cases mentioned below
- NumPy is the only library which can be imported. Inbuilt functions which require no import and Datatype methods can be used to solve this problem but No arbitray functions or library can be used.
- You can use NumPy zeros() method to for the solution to solve this problem.

**Input Array**

[[1 2]
[3 4]
[5 6]] 

**Expected Outcome** 

[[0. 0.]
 [0. 0.]
 [0. 0.]]




In [ ]:
import numpy as np

def create_duplicate_array_of_ones(input_array):
  if input_array is not None and type(input_array[0]) is np.ndarray:
    output = list()
    for arr in input_array:
      output.append(np.zeros(len(arr)))
    return np.array(output)
  return np.zeros(len(input_array))


input_array_tuple_list = [np.array([[1, 2], [3, 4]]), np.array([5, 6])]
for input_array in input_array_tuple_list:
    output_array = create_duplicate_array_of_ones(input_array=input_array)
    print("Input Array: \n{0} \nDuplicated Arrays in Ones: \n{1}\n\n".format(input_array, output_array))

Input Array: 
[[1 2]
 [3 4]] 
Duplicated Arrays in Ones: 
[[0. 0.]
 [0. 0.]]


Input Array: 
[5 6] 
Duplicated Arrays in Ones: 
[0. 0.]




## Q3: Build a k-fold validation neural network using Keras

- Use the dataset: data_01.csv
- Split the columns into 60 input variables (input_x) and 1 output variable (output_y)
- The output variable has string values; hence convert them into integer values 0 and 1.
- You can select the number of hidden layers, activation functions, optimizer, batch size, and epochs of your choice.
- Neural network paramaters: loss=binary_crossentropy, metrics=accuracy, n_splits=10.

**Expected Output**
- Mean accuracy: Greater than 80%.

In [ ]:
import numpy as np
from pandas import read_csv
from keras.models import Sequential
from keras.layers import Dense

data = read_csv("data_01.csv", header=None)
dataset = data.values

input_x = dataset[:,0:60].astype(int)
output_y = dataset[:,59].astype(int)

kfold = StratifiedKFold(n_splits=10, shuffle=True)
cross_validationores_scores = []

for train, test in kfold.split(input_x, output_y):
	model = Sequential()
	model.add(Dense(12, input_dim=60, activation='relu'))
	model.add(Dense(60, activation='relu'))
	model.add(Dense(1, activation='sigmoid'))
 
	model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])
 
	model.fit(input_x[train], output_y[train], epochs=150, batch_size=10, verbose=0)
 
	scores = model.evaluate(input_x[test], output_y[test], verbose=0)
 
	print("%s: %.2f%%" % (model.metrics_names[1], scores[1]*100))
	cross_validationores_scores.append(scores[1] * 100)
 
print("%.2f%% (+/- %.2f%%)" % (np.mean(cross_validationores_scores), np.std(cross_validationores_scores)))

ValueError: ignored

## Q4: Build a neural network by splitting the data using Keras

- Use the dataset: data_02.csv
- Split the columns into 34 input variables (input_x) and 1 output variable (output_y)
- The output variable has string values; hence convert them into integer values 0 and 1.
- You can select the number of hidden layers, activation functions, optimizer, batch size, and epochs of your choice.
- Neural network paramaters: loss=binary_crossentropy, metrics=accuracy, validation_split=0.33.

**Expected Output**
- Validation accuracy: Greater than 98%.

In [ ]:
# write your code here
from pandas import read_csv
from keras.models import Sequential
from keras.layers import Dense
from keras.wrappers.scikit_learn import KerasClassifier
from keras.utils import np_utils
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import KFold
from sklearn.preprocessing import LabelEncoder

data = read_csv("data_02.csv", header=None)
dataset = data.values

input_x = dataset[:,0:34].astype(int)
output_y = dataset[:,33].astype(int)

encoding = LabelEncoder()
encoding.fit(output_y)
encoded_y = encoding.transform(output_y)

# perform one hot encoding by converting convert integers to dummy variables
dummy_output_y = np_utils.to_categorical(encoded_y)

# define function baseline
def baseline():
	model = Sequential()
	model.add(Dense(8, input_dim=34, activation='relu'))
	model.add(Dense(3, activation='softmax'))
 
	# Compile model
	model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])
	return model

estimator = KerasClassifier(build_fn=baseline, epochs=200, batch_size=5, verbose=0)

kfold = KFold(n_splits=10, shuffle=True)

prediction = cross_val_score(estimator, input_x, dummy_output_y, cv=kfold)

print("Accuracy: %.2f%% (%.2f%%)" % (prediction.mean()*100, prediction.std()*100))

Accuracy: 94.02% (2.96%)
