<a href="https://colab.research.google.com/github/vivianconrad/neural-networks-and-deep-learning/blob/main/Introduction_to_NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Basics of Numpy

- The basic data structure used in NumPy is the ndarray,
which stands for N-dimensional array. It is a fixed-sized array in memory that contains data of the same type, such as integers or floating point values.

- The data type supported by an array can be accessed via the **.dtype** attribute on the array.
The dimensions of an array can be accessed via the **.shape** attribute that returns a tuple describing the length of each dimension.

In [ ]:
# Import NumPy library, which will be use across all parts of this notebook
import numpy as np

## Part - 1: Array Creation, Generation and Combination.


In [ ]:
# Create a list of values
list_of_values = [1.0, 2.0, 3.0]
# Convert the list to an array of values
array_of_values = np.array(list_of_values)
# Display array
print("1-D Array Values:\n", array_of_values)
# Display array shape - Represents the dimension of the array
print("\n1-D  Array Shape:", array_of_values.shape)
# Display array data type - Represents the type of values present in the array
print("\n1-D  Array Data Type:", array_of_values.dtype)

1-D Array Values:
 [1. 2. 3.]

1-D  Array Shape: (3,)

1-D  Array Data Type: float64


In [ ]:
# Create a list of values
list_of_values = [[1.0, 2.0, 3.0], [4.0, 5.0, 6.0], [7.0, 8.0, 9.0], [1.1, 2.2, 3.3]]
# Convert the list to an array of values
array_of_values = np.array(list_of_values)
# Display array
print("2-D  Array Values:\n", array_of_values)
# Display array shape - Represents the dimension of the array - (Rows, Columns)
print("\n2-D Array Shape:", array_of_values.shape)
# Display array data type - Represents the type of values present in the array
print("\n2-D Array Data Type:", array_of_values.dtype)

2-D  Array Values:
 [[1.  2.  3. ]
 [4.  5.  6. ]
 [7.  8.  9. ]
 [1.1 2.2 3.3]]

2-D Array Shape: (4, 3)

2-D Array Data Type: float64


In [ ]:
# We will see what happens when one element of the list we try to convert to array is not in the format we expect it to

# Create a list of values - Here '4.0' is a string when rest are float values
list_of_values = [[1.0, 2.0, 3.0], ['4.0', 5.0, 6.0], [7.0, 8.0, 9.0], [1.1, 2.2, 3.3]]
# Convert the list to an array of values
array_of_values = np.array(list_of_values)
# Display array - All values are shown to be converted to string
print("2-D  Array Values:\n", array_of_values)
# Display array shape - Represents the dimension of the array - (Rows, Columns)
print("\n2-D Array Shape:", array_of_values.shape)
# Display array data type - Represents the type of values present in the array
print("\n2-D Array Data Type:", array_of_values.dtype)

# This is important to remember because when you see data being converted to an array not being in the format you expect to be then 
# Investigate all the elements to be of the same datatype

2-D  Array Values:
 [['1.0' '2.0' '3.0']
 ['4.0' '5.0' '6.0']
 ['7.0' '8.0' '9.0']
 ['1.1' '2.2' '3.3']]

2-D Array Shape: (4, 3)

2-D Array Data Type: <U32


In [ ]:
# We will see what happens when one element of the list we try to convert to array is not in the format we expect it to

# Create a list of values - Here [4, 5, 6] are integers when rest are float values
list_of_values = [[1.0, 2.0, 3.0], [4, 5, 6], [7, 8, 9], [1.1, 2.2, 3.3]]
# Convert the list to an array of values
array_of_values = np.array(list_of_values)
# Display array - All values are shown to be converted to float
print("2-D  Array Values:\n", array_of_values)
# Display array shape - Represents the dimension of the array - (Rows, Columns)
print("\n2-D Array Shape:", array_of_values.shape)
# Display array data type - Represents the type of values present in the array
print("\n2-D Array Data Type:", array_of_values.dtype)

# This is important to remember because when you see data being converted to an array not being in the format you expect to be then 
# Investigate all the elements to be of the same datatype

2-D  Array Values:
 [[1.  2.  3. ]
 [4.  5.  6. ]
 [7.  8.  9. ]
 [1.1 2.2 3.3]]

2-D Array Shape: (4, 3)

2-D Array Data Type: float64


### Array Generation
- So far we have create arrays from lists that we have already defined hence we basically converted a list to obtain an array but now we will check out how to make an array using the many create array functions present in NumPy.
The following are how we generate arrays
    - **empty()** - This function will create random valued float array of the dimension provided as input
    - **zeros()** - This function will create an array where all values are 0 of the dimension provided as input
    - **ones()** - This function will create an array where all values are 1 of the dimension provided as input

In [ ]:
# We will create an array is the empty() function - This will create random valued float array of the dimension we provide

# Generate an array for the dimension (2, )
array_of_values = np.empty((2,))
# Display array - All values are shown to be converted to float
print("1-D  Array Values:\n", array_of_values)
# Display array shape - Represents the dimension of the array - (Rows, Columns)
print("\n1-D Array Shape:", array_of_values.shape)
# Display array data type - Represents the type of values present in the array
print("\n1-D Array Data Type:", array_of_values.dtype)

# Generate an array for the dimension (3, 5)
array_of_values = np.empty((3, 5))
# Display array - All values are shown to be converted to float
print("\n2-D  Array Values:\n", array_of_values)
# Display array shape - Represents the dimension of the array - (Rows, Columns)
print("\n2-D Array Shape:", array_of_values.shape)
# Display array data type - Represents the type of values present in the array
print("\n2-D Array Data Type:", array_of_values.dtype)

1-D  Array Values:
 [1.61430377e-316 0.00000000e+000]

1-D Array Shape: (2,)

1-D Array Data Type: float64

2-D  Array Values:
 [[1.61558359e-316 1.03977794e-312 1.01855798e-312 9.54898106e-313
  1.18831764e-312]
 [1.03977794e-312 1.23075756e-312 1.03977794e-312 1.12465777e-312
  9.76118064e-313]
 [1.18831764e-312 1.18831764e-312 1.08221785e-312 4.44659081e-322
  0.00000000e+000]]

2-D Array Shape: (3, 5)

2-D Array Data Type: float64


In [ ]:
# We will create an array is the zeros() function - This will create 0 valued array of the dimension we provide

# Generate an array for the dimension (2, )
array_of_values = np.zeros((2,))
# Display array - All values are shown to be converted to float
print("1-D  Array Values:\n", array_of_values)
# Display array shape - Represents the dimension of the array - (Rows, Columns)
print("\n1-D Array Shape:", array_of_values.shape)
# Display array data type - Represents the type of values present in the array
print("\n1-D Array Data Type:", array_of_values.dtype)

# Generate an array for the dimension (3, 5)
array_of_values = np.zeros((3, 5))
# Display array - All values are shown to be converted to float
print("\n2-D  Array Values:\n", array_of_values)
# Display array shape - Represents the dimension of the array - (Rows, Columns)
print("\n2-D Array Shape:", array_of_values.shape)
# Display array data type - Represents the type of values present in the array
print("\n2-D Array Data Type:", array_of_values.dtype)

1-D  Array Values:
 [0. 0.]

1-D Array Shape: (2,)

1-D Array Data Type: float64

2-D  Array Values:
 [[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]

2-D Array Shape: (3, 5)

2-D Array Data Type: float64


In [ ]:
# We will create an array is the ones() function - This will create 1 valued array of the dimension we provide

# Generate an array for the dimension (2, )
array_of_values = np.ones((2,))
# Display array - All values are shown to be converted to float
print("1-D  Array Values:\n", array_of_values)
# Display array shape - Represents the dimension of the array - (Rows, Columns)
print("\n1-D Array Shape:", array_of_values.shape)
# Display array data type - Represents the type of values present in the array
print("\n1-D Array Data Type:", array_of_values.dtype)

# Generate an array for the dimension (3, 5)
array_of_values = np.ones((3, 5))
# Display array - All values are shown to be converted to float
print("\n2-D  Array Values:\n", array_of_values)
# Display array shape - Represents the dimension of the array - (Rows, Columns)
print("\n2-D Array Shape:", array_of_values.shape)
# Display array data type - Represents the type of values present in the array
print("\n2-D Array Data Type:", array_of_values.dtype)

1-D  Array Values:
 [1. 1.]

1-D Array Shape: (2,)

1-D Array Data Type: float64

2-D  Array Values:
 [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]

2-D Array Shape: (3, 5)

2-D Array Data Type: float64


### Array Combination
- Now that we have a firm idea on how to create arrays, We will further learn how to combine two or more arrays to create new arrays.
- We can combine arrays by Vertically (vstach) stacking the rows
- We can combine arrays by Horizontally (hstack) stacking the columns


In [ ]:
# Generate an array for the dimension (3, 5)
array_1_of_values = np.array([[1, 2, 3], [4, 5, 6]])
# Display array - All values are shown to be converted to float
print("2-D  Array Values:\n", array_1_of_values)
# Display array shape - Represents the dimension of the array - (Rows, Columns)
print("\n2-D Array Shape:", array_1_of_values.shape)
# Display array data type - Represents the type of values present in the array
print("\n2-D Array Data Type:", array_1_of_values.dtype)

# Generate an array for the dimension (3, 5)
array_2_of_values = np.array([[1.1, 2.2, 3.3], [4.4, 5.5, 6.6]])
# Display array - All values are shown to be converted to float
print("\n2-D  Array Values:\n", array_2_of_values)
# Display array shape - Represents the dimension of the array - (Rows, Columns)
print("\n2-D Array Shape:", array_2_of_values.shape)
# Display array data type - Represents the type of values present in the array
print("\n2-D Array Data Type:", array_2_of_values.dtype)

2-D  Array Values:
 [[1 2 3]
 [4 5 6]]

2-D Array Shape: (2, 3)

2-D Array Data Type: int64

2-D  Array Values:
 [[1.1 2.2 3.3]
 [4.4 5.5 6.6]]

2-D Array Shape: (2, 3)

2-D Array Data Type: float64


In [ ]:
# Generate an array for the dimension (3, 5)
array_of_values = np.vstack((array_1_of_values, array_2_of_values))
# Display array - All values are shown to be converted to float
print("2-D  Array Values:\n", array_of_values)
# Display array shape - Represents the dimension of the array - (Rows, Columns)
print("\n2-D Array Shape:", array_of_values.shape)
# Display array data type - Represents the type of values present in the array
print("\n2-D Array Data Type:", array_of_values.dtype)

2-D  Array Values:
 [[1.  2.  3. ]
 [4.  5.  6. ]
 [1.1 2.2 3.3]
 [4.4 5.5 6.6]]

2-D Array Shape: (4, 3)

2-D Array Data Type: float64


In [ ]:
# Generate an array for the dimension (3, 5)
array_of_values = np.hstack((array_1_of_values, array_2_of_values))
# Display array - All values are shown to be converted to float
print("\n2-D  Array Values:\n", array_of_values)
# Display array shape - Represents the dimension of the array - (Rows, Columns)
print("\n2-D Array Shape:", array_of_values.shape)
# Display array data type - Represents the type of values present in the array
print("\n2-D Array Data Type:", array_of_values.dtype)


2-D  Array Values:
 [[1.  2.  3.  1.1 2.2 3.3]
 [4.  5.  6.  4.4 5.5 6.6]]

2-D Array Shape: (2, 6)

2-D Array Data Type: float64


## Part - 2: Indexing, Slicing and Reshaping Arrays.
- An array is a sequence of values and each element in the array is present at an index value where the first element is present at 0th index and the Nth element in present at the (N-1)th position.
- Next we will learn to transform the shape of the array itself to any other desired dimension.

In [ ]:
# Create a list of values
list_of_values = [1.0, 2.0, 3.0]
# Display list
print("List of values:\n", list_of_values)
# We can generally index lists values
print("0th Index Value in List:", list_of_values[0])
print("1st Index Value in List:", list_of_values[1])
print("2nd Index Value in List:", list_of_values[2])

# Convert the list to an array of values
array_of_values = np.array(list_of_values)
# Display array
print("\n1-D Array Values:\n", array_of_values)
# We can also index lists values
print("0th Index Value in Array:", array_of_values[0])
print("1st Index Value in Array:", array_of_values[1])
print("2nd Index Value in Array:", array_of_values[2])

List of values:
 [1.0, 2.0, 3.0]
0th Index Value in List: 1.0
1st Index Value in List: 2.0
2nd Index Value in List: 3.0

1-D Array Values:
 [1. 2. 3.]
0th Index Value in Array: 1.0
1st Index Value in Array: 2.0
2nd Index Value in Array: 3.0


In [ ]:
# Display array
print("\n1-D Array Values:\n", array_of_values)
# Display array shape - Represents the dimension of the array - (Rows, Columns)
print("\n1-D Array Shape:", array_of_values.shape)
# Now we cannot access 10-1= 9th Index because there are only 9 elements present in the array of values
# Which means there are only 0-8 index available to be accessed
print("9th Index Value in Array:", array_of_values[10])
# This will throw index error because we are trying to access elements which are out of the bounds i.e length of the array


1-D Array Values:
 [1. 2. 3.]

1-D Array Shape: (3,)


IndexError: ignored

In [ ]:
# Display array
print("\n1-D Array Values:\n", array_of_values)
# Display array shape - Represents the dimension of the array - (Rows, Columns)
print("\n2-D Array Shape:", array_of_values.shape)
# Now we can access 9-1= 8th Index because there are only 9 elements present in the array of values
print("8th Index Value in Array:", array_of_values[8])
# This will not throw index error because we are trying to access elements which are in the of the bounds i.e length of the array


1-D Array Values:
 [1. 2. 3.]

2-D Array Shape: (3,)


IndexError: ignored

- Next we will look at list slicing where we get a section of the array from a START index to a STOP index value, By pythons logic the STOP index will be N-1 of whatever we provide
- Ex-1: If we slice the indexes from [0:5] then we are infact getting a section of the array from index 0 to index 5-1= 4
- Ex-2: If we slice the indexes from [3:7] then we are infact getting a section of the array from index 3 to index 7-1= 6

|        |      Index 0     |    Index 1   |    Index 2   |      Index 3     |     Index 4     |    Index 5   |     Index 6     |    Index 7   |    Index 8   |
|--------|:----------------:|:------------:|:------------:|:----------------:|:---------------:|:------------:|:---------------:|:------------:|:------------:|
|        |   0<br><br>1.0   | 1<br><br>2.0 | 2<br><br>3.0 |   3<br><br>4.1   |   4<br><br>5.1  | 5<br><br>6.1 |   6<br><br>7.2  | 7<br><br>8.2 | 8<br><br>9.2 |
| Ex-1:  | 1.0<br><br>START | 2.0          | 3.0          | 4.1              | 5.1<br><br>STOP |              |                 |              |              |
| Ex-2:  |                  |              |              | 4.1<br><br>START | 5.1             | 6.1          | 7.2<br><br>STOP |              |              |

In [ ]:
# Create a list of values
list_of_values = [1.0, 2.0, 3.0, 4.1, 5.1, 6.1, 7.2, 8.2, 9.2]
# Convert the list to an array of values
array_of_values = np.array(list_of_values)
# Display array
print("\n1-D Array Values:\n", array_of_values)
# We slice sections from the list [start_index: end_index: step_index]
print("0th Index Value:", array_of_values[0:5]) # This slices represents values from 0th index to 5-1= 4th index
print("1st Index Value:", array_of_values[3:7]) # This slices represents values from 3th index to 7-1= 6th index


1-D Array Values:
 [1.  2.  3.  4.1 5.1 6.1 7.2 8.2 9.2]
0th Index Value: [1.  2.  3.  4.1 5.1]
1st Index Value: [4.1 5.1 6.1 7.2]


- We have seen how indexes work in 1-D array, Next we can visualize and better understand indexes when it comes to 2-D arrays with the sample table given below

|       |      Column 0     |      Column 1     |      Column 2     |
|:-----:|:-----------------:|:-----------------:|:-----------------:|
| Row 0 | 1.0<br><br>[0, 0] | 2.0<br><br>[0, 1] | 3.0<br><br>[0, 2] |
| Row 1 | 1.1<br><br>[1, 0] | 2.1<br><br>[1, 1] | 3.1<br><br>[1, 2] |
| Row 2 | 1.2<br><br>[2, 0] | 2.2<br><br>[2, 1] | 3.2<br><br>[2, 2] |

- We can see that how each row and column starts with index 0 and goes up to N-1th positions index value.


In [ ]:
# Create a list of values
list_of_values = [[1.0, 2.0, 3.0], [1.1, 2.1, 3.1], [1.2, 2.2, 3.2]]
# Convert the list to an array of values
array_of_values = np.array(list_of_values)
# Display array
print("\n1-D Array Values:\n", array_of_values)
# We can also index lists values
print("0th Row and 0th Column Index Value in Array:", array_of_values[0][0])
print("1st Row and 1st Column Value in Array:", array_of_values[1][1])
print("2nd Row and 2nd Column Index Value in Array:", array_of_values[2][2])


1-D Array Values:
 [[1.  2.  3. ]
 [1.1 2.1 3.1]
 [1.2 2.2 3.2]]
0th Row and 0th Column Index Value in Array: 1.0
1st Row and 1st Column Value in Array: 2.1
2nd Row and 2nd Column Index Value in Array: 3.2


In [ ]:
# Create a list of values
list_of_values = [[1.0, 2.0, 3.0, 4.0, 5.0], [1.1, 2.1, 3.1, 4.1, 5.1], [1.2, 2.2, 3.2, 4.2, 5.2], [1.3, 2.3, 3.3, 4.3, 5.3]]
# Convert the list to an array of values
array_of_values = np.array(list_of_values)
# Display array
print("\n1-D Array Values:\n", array_of_values)
# We slice sections from the list [start_index: end_index: step_index]
print("0th Row and 2nd to 4th Column Index Value in Array:", array_of_values[0][2:5])


1-D Array Values:
 [[1.  2.  3.  4.  5. ]
 [1.1 2.1 3.1 4.1 5.1]
 [1.2 2.2 3.2 4.2 5.2]
 [1.3 2.3 3.3 4.3 5.3]]
0th Row and 2nd to 4th Column Index Value in Array: [3. 4. 5.]


In [ ]:
# Create a list of values
list_of_values = [[1.0, 2.0, 3.0, 4.0, 5.0], [1.1, 2.1, 3.1, 4.1, 5.1], [1.2, 2.2, 3.2, 4.2, 5.2], [1.3, 2.3, 3.3, 4.3, 5.3], [1.4, 2.4, 3.4, 4.4, 5.4], [1.5, 2.5, 3.5, 4.5, 5.5]]
# Convert the list to an array of values
array_of_values = np.array(list_of_values)
# Display array
print("\n1-D Array Values:\n", array_of_values)

# Usually we will come across this when splitting the dataset into train and test datasets
# consider we have a dataset of (6, 5) and wish to split 4 rows into train and 2 into test
train_array, test_array = array_of_values[:4], array_of_values[4:]
# Display array
print("\nTrain Array:", train_array)
# Display array
print("\nTest Array:", test_array)


1-D Array Values:
 [[1.  2.  3.  4.  5. ]
 [1.1 2.1 3.1 4.1 5.1]
 [1.2 2.2 3.2 4.2 5.2]
 [1.3 2.3 3.3 4.3 5.3]
 [1.4 2.4 3.4 4.4 5.4]
 [1.5 2.5 3.5 4.5 5.5]]

Train Array: [[1.  2.  3.  4.  5. ]
 [1.1 2.1 3.1 4.1 5.1]
 [1.2 2.2 3.2 4.2 5.2]
 [1.3 2.3 3.3 4.3 5.3]]

Test Array: [[1.4 2.4 3.4 4.4 5.4]
 [1.5 2.5 3.5 4.5 5.5]]


In [ ]:
array_of_values[4:]

array([[1.4, 2.4, 3.4, 4.4, 5.4],
       [1.5, 2.5, 3.5, 4.5, 5.5]])

### Reshaping Array
- We will now learn how to reshape our arrays from one shape to another
- Some algorithms, like the Long Short-Term Memory recurrent neural network in Keras, require input to be specified as a three-dimensional array comprised of samples, timesteps, and features.
- It is important to know how to reshape your NumPy arrays so that your data meets the expectation of specific Python libraries.

In [ ]:
# Create a list of values
list_of_values = [1.0, 2.0, 3.0, 4.1, 5.1, 6.1, 7.2, 8.2, 9.2]
# Convert the list to an array of values
array_of_values = np.array(list_of_values)
# Display array
print("\n1-D Array Values:\n", array_of_values)
# Display array
print("\n2-D Array Values After Reshape (9, 1):\n", array_of_values.reshape(9, 1))
# Display array
print("\n2-D Array Values After Reshape (3, 3):\n", array_of_values.reshape(3, 3))
# Display array
print("\n3-D Array Values After Reshape (3, 3, 1):\n", array_of_values.reshape(3, 3, 1))


1-D Array Values:
 [1.  2.  3.  4.1 5.1 6.1 7.2 8.2 9.2]

2-D Array Values After Reshape (9, 1):
 [[1. ]
 [2. ]
 [3. ]
 [4.1]
 [5.1]
 [6.1]
 [7.2]
 [8.2]
 [9.2]]

2-D Array Values After Reshape (3, 3):
 [[1.  2.  3. ]
 [4.1 5.1 6.1]
 [7.2 8.2 9.2]]

3-D Array Values After Reshape (3, 3, 1):
 [[[1. ]
  [2. ]
  [3. ]]

 [[4.1]
  [5.1]
  [6.1]]

 [[7.2]
  [8.2]
  [9.2]]]


In [ ]:
# Create a list of values
list_of_values = [[1.0, 2.0, 3.0, 4.0, 5.0], [1.1, 2.1, 3.1, 4.1, 5.1], [1.2, 2.2, 3.2, 4.2, 5.2], [1.3, 2.3, 3.3, 4.3, 5.3]]
# Convert the list to an array of values
array_of_values = np.array(list_of_values)
# Display array
print("\n2-D Array Values:\n", array_of_values)
# Display array
print("\n1-D Array Values After Reshape (1, 20):\n", array_of_values.reshape(1, 20))
# Display array
print("\n2-D Array Values After Reshape (2, 10):\n", array_of_values.reshape(2, 10))
# Display array
print("\n3-D Array Values After Reshape (10, 2, 1):\n", array_of_values.reshape(10, 2, 1))


2-D Array Values:
 [[1.  2.  3.  4.  5. ]
 [1.1 2.1 3.1 4.1 5.1]
 [1.2 2.2 3.2 4.2 5.2]
 [1.3 2.3 3.3 4.3 5.3]]

1-D Array Values After Reshape (1, 20):
 [[1.  2.  3.  4.  5.  1.1 2.1 3.1 4.1 5.1 1.2 2.2 3.2 4.2 5.2 1.3 2.3 3.3
  4.3 5.3]]

2-D Array Values After Reshape (2, 10):
 [[1.  2.  3.  4.  5.  1.1 2.1 3.1 4.1 5.1]
 [1.2 2.2 3.2 4.2 5.2 1.3 2.3 3.3 4.3 5.3]]

3-D Array Values After Reshape (10, 2, 1):
 [[[1. ]
  [2. ]]

 [[3. ]
  [4. ]]

 [[5. ]
  [1.1]]

 [[2.1]
  [3.1]]

 [[4.1]
  [5.1]]

 [[1.2]
  [2.2]]

 [[3.2]
  [4.2]]

 [[5.2]
  [1.3]]

 [[2.3]
  [3.3]]

 [[4.3]
  [5.3]]]


## Part - 3: Array Broadcasting and Padding.


In [ ]:
# You can perform arithmetic directly on NumPy arrays, such as addition and subtraction. For
# example, two arrays can be added together to create a new array where the values at each
# index are added together. For example, an array a can be defined as [1, 2, 3] and array b can be
# defined as [4, 5, 6] and adding together will result in a new array with the values [5, 7, 9].
# Note: These are arrays of the same shape

# Create a list of values
list_of_values = [1, 2, 3]
# Convert the list to an array of values
array_a_of_values = np.array(list_of_values)

# Create a list of values
list_of_values = [4, 5, 6]
# Convert the list to an array of values
array_b_of_values = np.array(list_of_values)

# Display Array
print("1-D Array A:\n", array_a_of_values)
print("\n1-D Array B:\n", array_b_of_values)
print("\n1-D Array A + 1-D Array B:\n", array_a_of_values + array_b_of_values)
print("\n1-D Array A - 1-D Array B:\n", array_a_of_values - array_b_of_values)
print("\n1-D Array A * 1-D Array B:\n", array_a_of_values * array_b_of_values)
print("\n1-D Array A / 1-D Array B:\n", array_a_of_values / array_b_of_values)

1-D Array A:
 [1 2 3]

1-D Array B:
 [4 5 6]

1-D Array A + 1-D Array B:
 [5 7 9]

1-D Array A - 1-D Array B:
 [-3 -3 -3]

1-D Array A * 1-D Array B:
 [ 4 10 18]

1-D Array A / 1-D Array B:
 [0.25 0.4  0.5 ]


In [ ]:
# We will now try to add arrays that are not of the same shape

# Create a list of values
list_of_values = [1, 2, 3]
# Convert the list to an array of values
array_a_of_values = np.array(list_of_values)

# Create a list of values
list_of_values = [4, 5, 6, 7]
# Convert the list to an array of values
array_b_of_values = np.array(list_of_values)

# Display Array
print("1-D Array A:\n", array_a_of_values)
print("\n1-D Array B:\n", array_b_of_values)
print("\n1-D Array A + 1-D Array B:\n", array_a_of_values + array_b_of_values)
# This will throw an error since the arrays are not of the same shape

# Strictly, arithmetic may only be performed on arrays that have the same dimensions and
# dimensions with the same size. This means that a one-dimensional array with the length of
# 10 can only perform arithmetic with another one-dimensional array with the length 10. This
# limitation on array arithmetic is quite limiting indeed. Thankfully, NumPy provides a built-in
# workaround to allow arithmetic between arrays with differing sizes.

1-D Array A:
 [1 2 3]

1-D Array B:
 [4 5 6 7]


ValueError: ignored

In [ ]:
# A single value or scalar can be used in arithmetic with a one-dimensional array. For example,
# we can imagine a one-dimensional array a with three values [a1, a2, a3] added to a scalar b.

# Create a list of values
list_of_values = [1, 2, 3]
# Convert the list to an array of values
array_a_of_values = np.array(list_of_values)

# Create a list of values
list_of_values = [4, 5, 6]
# Convert the list to an array of values
array_b_of_values = np.array(list_of_values)

# Display Array
print("1-D Array A:\n", array_a_of_values)
print("\n1-D Array B:\n", array_b_of_values)
print("\n1-D Array A + scalar (10):\n", array_a_of_values + 10) # Broadcasting where 10 is the scalar and array_a_of_values is the array
print("\n1-D Array B * scalar (2):\n", array_b_of_values * 2) # Broadcasting where 2 is the scalar and array_a_of_values is the array

1-D Array A:
 [1 2 3]

1-D Array B:
 [4 5 6]

1-D Array A + scalar (10):
 [11 12 13]

1-D Array B * scalar (2):
 [ 8 10 12]


- Consider a 2-D Array A

|  |  |  |
|------|:----:|:----:|
| a1,1 | a1,2 | a1,3 |
| a2,1 | a2,2 | a2,3 |

- And a 2-D Array B

|  |  |  |
|------|:----:|:----:|
| b1,1 | b1,2 | b1,3 |
| b2,1 | b2,2 | b2,3 |

- Array A + Array B would be logically summarised as the following

|  |  |  |
|------|:----:|:----:|
| a1,1 + b1,1 | a1,2 + b1,2 | a1,3 + b1,3 |
| a2,1 + b2,1 | a2,2 + b2,2 | a2,3 + b2,3 |

In [ ]:
# Create a list of values
list_of_values = [[1, 2, 3], [4, 5, 6]]
# Convert the list to an array of values
array_a_of_values = np.array(list_of_values)

# Display Array
print("2-D Array A:\n", array_a_of_values)
print("\n2-D Array A + Scalar (10):\n", array_a_of_values + 10) # Broadcasting where 10 is the scalar and array_a_of_values is the array

2-D Array A:
 [[1 2 3]
 [4 5 6]]

2-D Array A + Scalar (10):
 [[11 12 13]
 [14 15 16]]


In [ ]:
# Create a list of values
list_of_values = [[1, 2, 3], [4, 5, 6]]
# Convert the list to an array of values
array_a_of_values = np.array(list_of_values)

# Create a list of values
list_of_values = [20, 40, 60]
# Convert the list to an array of values
array_b_of_values = np.array(list_of_values)

# Display Array
print("2-D Array A:\n", array_a_of_values)
print("\n2-D Array A + 1-D Array B:\n", array_a_of_values + array_b_of_values) # Broadcasting where 10 is the scalar and array_a_of_values is the array

2-D Array A:
 [[1 2 3]
 [4 5 6]]

2-D Array A + 1-D Array B:
 [[21 42 63]
 [24 45 66]]


**Note**: There are even limitations to broadcasting in NumPy where 
- Consider an Array A of shape: (2, 3)
- Consider a Scalar B of shape: (3) or Array of shape (1, 3)
    - Scalar B of shape (3) is infact comprehended as (1, 3)
- Now (2, **3**) and (1, **3**) have their coloumn values match
- Hence we can apply arithemetic operations on it.
- But we cannot perform operations on arrays that do not match the above criteria of column values matching as shown in the error above