<a href="https://colab.research.google.com/github/vivianconrad/neural-networks-and-deep-learning/blob/main/Introduction_to_GAN_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Upsample Layer

In [ ]:
from numpy import asarray
from keras.models import Sequential
from keras.layers import UpSampling2D


input_data = asarray([[1, 2],
			 [3, 4]])
print(input_data)

reshape_input = input_data.reshape((1, 2, 2, 1))

model = Sequential()
model.add(UpSampling2D(input_shape=(2, 2, 1)))
model.summary()

prediction = model.predict(reshape_input)
prediction = prediction.reshape((4, 4))
print(prediction)

[[1 2]
 [3 4]]
Model: "sequential_9"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
up_sampling2d_9 (UpSampling2 (None, 4, 4, 1)           0         
Total params: 0
Trainable params: 0
Non-trainable params: 0
_________________________________________________________________
[[1. 1. 2. 2.]
 [1. 1. 2. 2.]
 [3. 3. 4. 4.]
 [3. 3. 4. 4.]]


# Upsample Generator

In [ ]:
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import Reshape
from keras.layers import UpSampling2D
from keras.layers import Conv2D


model = Sequential()
# input shape, output activations for 128 7x7 image
model.add(Dense(128 * 7 * 7, input_dim=100))
# reshaping vector of activations into 128 feature maps with 7x7
model.add(Reshape((7, 7, 128)))
# doubling the input from 128 5x5 to 1 10x10 feature map
model.add(UpSampling2D())
# filling the upsampled feature maps and output a single image
model.add(Conv2D(1, (3,3), padding='same'))
model.summary()

Model: "sequential_15"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_5 (Dense)              (None, 6272)              633472    
_________________________________________________________________
reshape_5 (Reshape)          (None, 7, 7, 128)         0         
_________________________________________________________________
up_sampling2d_14 (UpSampling (None, 14, 14, 128)       0         
_________________________________________________________________
conv2d_4 (Conv2D)            (None, 14, 14, 1)         1153      
Total params: 634,625
Trainable params: 634,625
Non-trainable params: 0
_________________________________________________________________


# Transpose Layer

In [ ]:

from numpy import asarray
from keras.models import Sequential
from keras.layers import Conv2DTranspose

X = asarray([[1, 2],
			 [3, 4]])

print(X)

X = X.reshape((1, 2, 2, 1))

model = Sequential()
model.add(Conv2DTranspose(1, (1,1), strides=(2,2), input_shape=(2, 2, 1)))
model.summary()

# defining weights that they do nothing
weights = [asarray([[[[1]]]]), asarray([0])]

# storing the weights in the model
model.set_weights(weights)

# making a prediction with the model
yhat = model.predict(X)

# reshaping output to remove channel to make printing easier
yhat = yhat.reshape((4, 4))

# summarizing output
print(yhat)

[[1 2]
 [3 4]]
Model: "sequential_16"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d_transpose (Conv2DTran (None, 4, 4, 1)           2         
Total params: 2
Trainable params: 2
Non-trainable params: 0
_________________________________________________________________
[[1. 0. 2. 0.]
 [0. 0. 0. 0.]
 [3. 0. 4. 0.]
 [0. 0. 0. 0.]]


# Transpose Generator

In [ ]:
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import Reshape
from keras.layers import Conv2DTranspose

model = Sequential()
model.add(Dense(128 * 5 * 5, input_dim=100))
# reshaping vector of activations into 128 feature maps with 5x5
model.add(Reshape((5, 5, 128)))
# doubling the input from 128 5x5 to 1 10x10 feature map
model.add(Conv2DTranspose(1, (3,3), strides=(2,2), padding='same'))
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense (Dense)                (None, 3200)              323200    
_________________________________________________________________
reshape (Reshape)            (None, 5, 5, 128)         0         
_________________________________________________________________
conv2d_transpose (Conv2DTran (None, 10, 10, 1)         1153      
Total params: 324,353
Trainable params: 324,353
Non-trainable params: 0
_________________________________________________________________


 # Strided Downsample

In [ ]:
from keras.models import Sequential
from keras.layers import Conv2D
model = Sequential()
model.add(Conv2D(64, (3,3), strides=(2,2), padding='same', input_shape=(64,64,3)))
model.summary()

# Strided Upsample

In [ ]:
from keras.models import Sequential
from keras.layers import Conv2DTranspose
model = Sequential()
model.add(Conv2DTranspose(64, (4,4), strides=(2,2), padding='same', input_shape=(64,64,3)))
model.summary()

## Leaky Relu

In [ ]:
from keras.models import Sequential
from keras.layers import Conv2D
from keras.layers import LeakyReLU
model = Sequential()
model.add(Conv2D(64, (3,3), strides=(2,2), padding='same', input_shape=(64,64,3)))
model.add(LeakyReLU(0.2))
model.summary()

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d (Conv2D)              (None, 32, 32, 64)        1792      
_________________________________________________________________
leaky_re_lu (LeakyReLU)      (None, 32, 32, 64)        0         
Total params: 1,792
Trainable params: 1,792
Non-trainable params: 0
_________________________________________________________________


# Batch Normalization

In [ ]:
from keras.models import Sequential
from keras.layers import Conv2D
from keras.layers import BatchNormalization
from keras.layers import LeakyReLU
model = Sequential()
model.add(Conv2D(64, (3,3), strides=(2,2), padding='same', input_shape=(64,64,3)))
model.add(BatchNormalization())
#standardizes the activations from a prior layer to have a zero mean and unit variance.
model.add(LeakyReLU(0.2))
model.summary()

Model: "sequential_3"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d_2 (Conv2D)            (None, 32, 32, 64)        1792      
_________________________________________________________________
batch_normalization_1 (Batch (None, 32, 32, 64)        256       
_________________________________________________________________
leaky_re_lu_2 (LeakyReLU)    (None, 32, 32, 64)        0         
Total params: 2,048
Trainable params: 1,920
Non-trainable params: 128
_________________________________________________________________


# Gaussian Weight Initilization

In [ ]:
from keras.models import Sequential
from keras.layers import Conv2DTranspose
from keras.initializers import RandomNormal

model = Sequential()
init = RandomNormal(mean=0.0, stddev=0.02)
model.add(Conv2DTranspose(64, (4,4), strides=(2,2), padding='same', kernel_initializer=init, input_shape=(64,64,3)))

# Adam Optimizer

In [ ]:
from keras.models import Sequential
from keras.layers import Conv2D
from keras.optimizers import Adam

model = Sequential()
model.add(Conv2D(64, (3,3), strides=(2,2), padding='same', input_shape=(64,64,3)))

opt = Adam(lr=0.0002, beta_1=0.5)
model.compile(loss='binary_crossentropy', optimizer=opt, metrics=['accuracy'])

Acknowledgement: Jason Brownlee, Generative Adversarial Networks with Python, Machine Learning Mastery, Available from https://machinelearningmastery.com/generative_adversarial_networks/, accessed  March 15th, 2021.