## Question - 1
Write Python code that does the following. 

- Create a function called **create_duplicate_array_of_ones** which accpets **input_array** as a parameter, where input_array is a NumPy array and we will return a NumPy array made up of ones with the same dimensions

Ex-1: Consider input_array=[1, 2, 3], which is provided to the function **create_duplicate_array_of_ones**
- We will create an array of ones of similar shape i.e [1.0, 1.0, 1.0] and then return this value
- Hence the output is [1.0, 1.0, 1.0]

Ex-2: Consider input_array=[[1, 2], [3, 4]], which is provided to the function **create_duplicate_array_of_ones**
- We will create an array of ones of similar shape i.e [[1.0, 1.0], [1.0, 1.0]] and then return this value
- Hence the output is [[1.0, 1.0], [1.0, 1.0]]


**Conditions to follow:**
- The output should be data structure format similar to test cases mentioned below
- NumPy is the only library which can be imported. Inbuilt functions which require no import and Datatype methods can be used to solve this problem but No arbitray functions or library can be used.
- The code you write should pass all the test cases given.


---

TEST CASES:

```
Input Array: 
[[1 4]
 [2 5]] 
Duplicated Arrays in Ones: 
[[1. 1.]
 [1. 1.]]


Input Array: 
[5.5 6.6] 
Duplicated Arrays in Ones: 
[1. 1.]


Input Array: 
['2' '4' '6'] 
Duplicated Arrays in Ones: 
[1. 1. 1.]
```
---

Hint: You can use NumPy ones() method to for the solution to solve this problem.


### Code

In [ ]:
# Import NumPy as np
import numpy as np

# DECLARE create_duplicate_array_of_ones function which taken in an input array 
def create_duplicate_array_of_ones(input_array):
  if input_array is not None and type(input_array[0]) is np.ndarray:
    output = list()
    for arr in input_array:
      output.append(np.ones(len(arr)))
    return np.array(output)
  return np.ones(len(input_array))

### TEST CASES ###

# Initialize the input values
input_array_tuple_list = [np.array([[1, 4], [2, 5]]), np.array([5.5, 6.6]), np.array(['2', '4', '6'])]
for input_array in input_array_tuple_list:
    # CALL the create_duplicate_array_of_ones with required parameters
    output_array = create_duplicate_array_of_ones(input_array=input_array)
    # Print the output
    print("Input Array: \n{0} \nDuplicated Arrays in Ones: \n{1}\n\n".format(input_array, output_array))

Input Array: 
[[1 4]
 [2 5]] 
Duplicated Arrays in Ones: 
[[1. 1.]
 [1. 1.]]


Input Array: 
[5.5 6.6] 
Duplicated Arrays in Ones: 
[1. 1.]


Input Array: 
['2' '4' '6'] 
Duplicated Arrays in Ones: 
[1. 1. 1.]




## Question - 2
Write Python code that does the following. 

- Create a function called **create_train_test_array_split** which accpets **input_array** and **train_array_ratio** as a parameter, where input_array is a NumPy array and **train_array_ratio** will be the fraction in which the input_array shape will be split, we will return a two arrays after splitting the input array shape using the train_array_ratio.
- Note: The input_array will only be 1-D and 2-D arrays.

Ex-1: Consider input_array=[1, 2, 3, 4, 5, 6], and train_array_ratio=0.5 which is provided to the function **create_train_test_array_split**
- We will split this according the shape i.e size of the 1-D array which here is 6 so 0.5 of 6 is 3
- Hence we will have train_array=[1, 2, 3] (index 0 to index 2 - Total 3 elements) and test_array=[4, 5, 6] (index 3 to index 5 - Total 3 elements)
- Hence the output is train_array=[1, 2, 3] and test_array=[4, 5, 6]

Ex-2: Consider input_array=[[1, 2], [3, 4], [5, 6], [7, 8], [9, 10], [-1, -2], [-3, -4], [-5, -6], [-7, -8], [-9, -10]], and train_array_ratio=0.8 which is provided to the function **create_train_test_array_split**
- We will split this according the shape i.e size of the 2-D array which here is (10, 2) and we will consider the rows aspect so 0.8 of 10 is 8
- Hence we will have train_array=[1, 2], [3, 4], [5, 6], [7, 8], [9, 10], [-1, -2], [-3, -4], [-5, -6]] (index 0 to index 7 - Total 8 elements) and test_array=[[-7, -8], [-9, -10]] (index 7 to index 9 - Total 2 elements)
- Hence the output is train_array=[1, 2], [3, 4], [5, 6], [7, 8], [9, 10], [-1, -2], [-3, -4], [-5, -6]] and test_array=[[-7, -8], [-9, -10]]

**Conditions to follow:**
- The output should be data structure format similar to test cases mentioned below
- NumPy is the only library which can be imported. Inbuilt functions which require no import and Datatype methods can be used to solve this problem but No arbitray functions or library can be used.
- The code you write should pass all the test cases given.


---

TEST CASES:

```
Input Array: 
[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]] 
Split Ratio: 0.5 
Train Array: 
[[1 2]
 [3 4]
 [5 6]] 
Test Array: 
[[ 7  8]
 [ 9 10]
 [11 12]]


Input Array: 
[0.  1.1 2.2 3.3 4.4 5.5 6.6 7.7 8.8 9.9] 
Split Ratio: 0.8 
Train Array: 
[0.  1.1 2.2 3.3 4.4 5.5 6.6 7.7] 
Test Array: 
[8.8 9.9]


Input Array: 
['2' '4' '6' '8' '10' '12'] 
Split Ratio: 0.4 
Train Array: 
['2' '4'] 
Test Array: 
['6' '8' '10' '12']
```
---

Hint: You can use NumPy array slicing method to for the solution to solve this problem.


### Code

In [ ]:
# Import NumPy as np
import numpy as np

# DECLARE create_train_test_array_split function which taken in an input array 
def create_train_test_array_split(input_array, train_array_ratio):
  new_array_length = int(len(input_array)*train_array_ratio)
  train_array = np.array(input_array[:new_array_length])
  test_array= np.array(input_array [new_array_length:])
  return train_array, test_array
### TEST CASES ###

# Initialize the input values
input_array_tuple_list = [(np.array([[1, 2], [3, 4], [5, 6], [7, 8], [9, 10], [11, 12]]), 0.5), (np.array([0.0, 1.1, 2.2, 3.3, 4.4, 5.5, 6.6, 7.7, 8.8, 9.9]), 0.8), (np.array(['2', '4', '6', '8', '10', '12']), 0.4)]
for input_array, train_array_ratio in input_array_tuple_list:
    # CALL the create_duplicate_array_of_ones with required parameters
    train_array, test_array = create_train_test_array_split(input_array=input_array, train_array_ratio=train_array_ratio)
    # Print the output
    print("Input Array: \n{0} \nSplit Ratio: {1} \nTrain Array: \n{2} \nTest Array: \n{3}\n\n".format(input_array, train_array_ratio, train_array, test_array))

Input Array: 
[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]] 
Split Ratio: 0.5 
Train Array: 
[[1 2]
 [3 4]
 [5 6]] 
Test Array: 
[[ 7  8]
 [ 9 10]
 [11 12]]


Input Array: 
[0.  1.1 2.2 3.3 4.4 5.5 6.6 7.7 8.8 9.9] 
Split Ratio: 0.8 
Train Array: 
[0.  1.1 2.2 3.3 4.4 5.5 6.6 7.7] 
Test Array: 
[8.8 9.9]


Input Array: 
['2' '4' '6' '8' '10' '12'] 
Split Ratio: 0.4 
Train Array: 
['2' '4'] 
Test Array: 
['6' '8' '10' '12']




## Question - 3
Write Python code that does the following. 

- Create a function called **array_to_the_power** which accepts **input_array** and **power** as parameter, where input_array is a NumPy array and power can be both a scalar as well as array value

Ex-1: Consider input_array=[1, 2, 3], and power=2 which is provided to the function **array_to_the_power**
- We will create an array of input_array values all raised to the power of power parameter and then return this value which is [1, 2, 3] to the power 2 is [1, 4, 9]
- Hence the output is [1, 4, 9]

Ex-2: Consider input_array=[[5, 2], [3, 4]], and power=[2, 3] which is provided to the function **array_to_the_power**
- We will create an array of input_array values all raised to the power of power parameter and then return this value which is [[5, 2], [3, 4]] to the power [2, 3] is [[25, 8], [9, 32]]
- Hence the output is [[25, 8], [9, 32]]


**Conditions to follow:**
- The output should be data structure format similar to test cases mentioned below
- NumPy is the only library which can be imported. Inbuilt functions which require no import and Datatype methods can be used to solve this problem but No arbitray functions or library can be used.
- The code you write should pass all the test cases given. 


---

TEST CASES:

```
Input Array: 
[1 2 3 4] 
Array to the Power of 2: 
[ 1  4  9 16]


Input Array: 
[[1.5 2.5]
 [3.5 4.5]] 
Array to the Power of [[-1 -2]
 [-3 -4]]: 
[[0.66666667 0.16      ]
 [0.02332362 0.00243865]]


Input Array: 
[3 5 7 9] 
Array to the Power of [2 5 6 8]: 
[       9     3125   117649 43046721]
```
---

Hint: You can use NumPy simple arithmetic operations for the solution to solve this problem.

### Code

In [ ]:
# Import NumPy as np
import numpy as np

# DECLARE array_to_the_power function which taken in an input array 
def array_to_the_power(input_array, power):
  return input_array**power



# Initialize the input values
input_array_tuple_list = [(np.array([1, 2, 3, 4]), 2), (np.array([[1.5, 2.5,], [3.5, 4.5]]) , np.array([[-1, -2], [-3, -4]])), (np.array([3, 5, 7, 9]), np.array([2, 5, 6, 8]))]
for input_array, power in input_array_tuple_list:
    # CALL the array_to_the_power with required parameters
    output_array = array_to_the_power(input_array=input_array, power=power)
    # Print the output
    print("Input Array: \n{0} \nArray to the Power of {1}: \n{2}\n\n".format(input_array, power, output_array))

Input Array: 
[1 2 3 4] 
Array to the Power of 2: 
[ 1  4  9 16]


Input Array: 
[[1.5 2.5]
 [3.5 4.5]] 
Array to the Power of [[-1 -2]
 [-3 -4]]: 
[[0.66666667 0.16      ]
 [0.02332362 0.00243865]]


Input Array: 
[3 5 7 9] 
Array to the Power of [2 5 6 8]: 
[       9     3125   117649 43046721]


