<a href="https://colab.research.google.com/github/vivianconrad/neural-networks-and-deep-learning/blob/main/Practice_Numpy_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Array Attributes

In [ ]:
import numpy as np
np.random.seed(0)  # seed value to maintain reproducibility

x1 = np.random.randint(10, size=8)  # One-dimensional array
x2 = np.random.randint(10, size=(2, 3))  # Two-dimensional array
x3 = np.random.randint(10, size=(2, 3, 4))  # Three-dimensional array

In [ ]:
print("x3 ndim: ", x3.ndim)  # ndarray.ndim: Number of array dimensions.
print("x3 shape:", x3.shape) # numpy.shape(a): Return the shape of an array.
print("x3 size: ", x3.size)  # ndarray.size: Number of elements in the array.
print("dtype:",   x3.dtype)  # https://numpy.org/doc/stable/reference/arrays.dtypes.html
print("itemsize:", x3.itemsize, "bytes") # itemsize,lists the size (in bytes) of each array element.
print("nbytes:", x3.nbytes, "bytes")  # nbytes, lists the total size (in bytes) of the array.

x3 ndim:  3
x3 shape: (2, 3, 4)
x3 size:  24
dtype: int64
itemsize: 8 bytes
nbytes: 192 bytes


## Array Indexing

In [ ]:
x1 = np.random.randint(10, size=8)
print(x1)
print(x1[0])
print(x1[4])
print(x1[-1])
print(x1[-2])


[0 1 9 9 0 4 7 3]
0
0
3
7


In [ ]:
x2 = np.random.randint(10, size=(2, 3))
print(x2)
print(x2[0, 0])
print(x2[1, 0])
print(x2[1, -1])

[[2 7 2]
 [0 0 4]]
2
0
4


In [ ]:
x2[0, 0] = 10
print(x2)

[[10  7  2]
 [ 0  0  4]]


In [ ]:
x1[0] = 5.694159  # this will be truncated!
print(x1)

[5 0 3 3 7 9 3 5]


## Array Slicing

### One-dimensional subarrays

In [ ]:
# x[start:stop:step]
y1 = np.arange(12)
print(y1)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


## Q1: Create a 1D array

Expected output: array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])


In [ ]:

q1 = np.arange(10)
print(q1)

[0 1 2 3 4 5 6 7 8 9]


In [ ]:
y2=x[:6] # first six elements
print(y2)

[0 1 2 3 4 5]


In [ ]:
y3=x[6:] # elements after index 6
print(y3)

[ 6  7  8  9 10 11]


In [ ]:
y4=x[4:8] # middle sub-array
print(y4)

[4 5 6 7]


In [ ]:
y5=x[::2] # every other element
print(y5)

[ 0  2  4  6  8 10]


In [ ]:
y6=x[1::2]  # every other element, starting at index 1
print(y6)

[ 1  3  5  7  9 11]


In [ ]:
y7=x[::-1]  # all elements, reversed
print(y7)

[11 10  9  8  7  6  5  4  3  2  1  0]


In [ ]:
y8=x[6::-2]  # reversed every other from index 6
print(y8)

[6 4 2 0]


## Q2: Extract all odd numbers from 1D array
- **Input** arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
- **Expected Output** array([1, 3, 5, 7, 9])

In [ ]:

arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])


arr[arr % 2 == 1]

array([1, 3, 5, 7, 9])

## Q3: Replace all odd numbers in arr with -1
- **Input** arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
- **Expected Output** [ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1]

In [ ]:

arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
arr[arr % 2 == 1] = -1
print(arr)

[ 0 -1  2 -1  4 -1  6 -1  8 -1]


## Q4: Replace all odd numbers in arr with -1 without changing arr
- **Input** arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
- **Expected Output** 
- [ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1]
- [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [ ]:

arr = np.arange(10)
out = np.where(arr % 2 == 1, -1, arr)
print(out)
print(arr)

[ 0 -1  2 -1  4 -1  6 -1  8 -1]
[0 1 2 3 4 5 6 7 8 9]


### Multi-dimensional subarrays

In [ ]:
x2 = np.random.randint(10, size=(4, 5))
print(x2)

[[7 3 2 7 2]
 [0 0 4 5 5]
 [6 8 4 1 4]
 [9 8 1 1 7]]


In [ ]:
z1=x2[:3, :4]  # three rows, four columns
print(z1)

[[7 3 2 7]
 [0 0 4 5]
 [6 8 4 1]]


In [ ]:
z2=x2[:4, ::2]  # all rows, every other column
print(z2)

[[7 2 2]
 [0 4 5]
 [6 4 4]
 [9 1 7]]


In [ ]:
z3=x2[::-1, ::-1] # subarray dimensions reversed together
print(z3)

[[7 1 1 8 9]
 [4 1 4 8 6]
 [5 5 4 0 0]
 [2 7 2 3 7]]


In [ ]:
z4=(x2[:, 1])  #second column of x2
print(z4)

[3 0 8 8]


In [ ]:
z5=x2[2, :] # third row of x2
print(z5)

[6 8 4 1 4]


In [ ]:
z6=(x2[1]) # same as x2[1, :]
print(z6)

[0 0 4 5 5]


In [ ]:
z7= x2[:2, :2] # extract 2 x 2 subarray
print(z7)

[[7 3]
 [0 0]]


In [ ]:
print(x2)

[[7 3 2 7 2]
 [0 0 4 5 5]
 [6 8 4 1 4]
 [9 8 1 1 7]]


In [ ]:
z8=x2
z8[0, 0] = 999
print(z8)

[[999   3   2   7   2]
 [  0   0   4   5   5]
 [  6   8   4   1   4]
 [  9   8   1   1   7]]


## Reshaping of Arrays

In [ ]:
a1 = np.arange(0, 16).reshape((4, 4)) #put the numbers 0 through 15 in a 4 x 4 grid. 
print(a1)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


In [ ]:
a2 = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
print(a2)
a3=a2.reshape((3, 3)) #Gives a new shape to an array without changing its data.
print(a3)

[1 2 3 4 5 6 7 8 9]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
a4 = a2[np.newaxis, :] #row vector via newaxis
print(a4)

[[1 2 3 4 5 6 7 8 9]]


In [ ]:
a5=a2[:, np.newaxis] #column vector via newaxis
print(a5)

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]


## Q5: Convert a 1D array to a 2D array with 2 rows
- **Input** np.arange(10)
- **Expected Output** 

array([[0, 1, 2, 3, 4],

[5, 6, 7, 8, 9]])

In [ ]:
z = np.arange(0, 10).reshape((2, 5)) 
print(z)

[[0 1 2 3 4]
 [5 6 7 8 9]]


## Array Concatenation

In [ ]:
b1 = np.array([1, 2, 3, 4, 5])
b2 = np.array([3, 2, 1, 4, 1])
np.concatenate([b1, b2])

array([1, 2, 3, 4, 5, 3, 2, 1, 4, 1])

In [ ]:
b3 = [901, 902, 903]
print(np.concatenate([b1, b2, b3]))

[  1   2   3   4   5   3   2   1   4   1 901 902 903]


In [ ]:
b4 = np.array([[1, 2, 3],
               [4, 5, 6]])
print(b4)

[[1 2 3]
 [4 5 6]]


In [ ]:
np.concatenate([b4, b4]) # concatenate along the first axis

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [ ]:
b5=np.concatenate([b4, b4], axis=1) # concatenate along the second axis (zero-indexed)
print(b5)

[[1 2 3 1 2 3]
 [4 5 6 4 5 6]]


In [ ]:
b6 = np.array([1, 2, 3])
b7 = np.array([[9, 8, 7],
               [6, 5, 4]])

np.vstack([b6, b7]) # vertically stack the arrays

array([[1, 2, 3],
       [9, 8, 7],
       [6, 5, 4]])

In [ ]:
b8 = np.array([[990],
              [990]])
np.hstack([b7, b8]) # horizontally stack the arrays

array([[  9,   8,   7, 990],
       [  6,   5,   4, 990]])

## Q6: Swap columns 1 and 2 in the array x
- **Input** x = np.arange(9).reshape(3,3)

In [ ]:
x = np.arange(9).reshape(3,3)
x[:, [1,0,2]]

array([[1, 0, 2],
       [4, 3, 5],
       [7, 6, 8]])

## Q7:  Reverse the rows of a 2D array x
- **Input** x=np.arange(9).reshape(3,3)

In [ ]:
x=np.arange(9).reshape(3,3)
y=x[::-1]
print(y)

[[6 7 8]
 [3 4 5]
 [0 1 2]]


## Array Splitting


In [ ]:
c1 = [1, 2, 3, 4, 5, 990, 990, 3, 2, 1]
c2, c3, c4 = np.split(c1, [5, 7]) # N split-points, leads to N + 1 subarrays.
print(c2, c3, c4)

[1 2 3 4 5] [990 990] [3 2 1]


In [ ]:
c5 = np.arange(25).reshape((5, 5))
print(c5)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


In [ ]:
c6, c7 = np.vsplit(c5, [2]) # vertical split
print(c6)
print(c7)

[[0 1 2 3 4]
 [5 6 7 8 9]]
[[10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


In [ ]:
c8, c9 = np.vsplit(c5, [2]) # vertical split
print(c8)
print(c9)

[[0 1 2 3 4]
 [5 6 7 8 9]]
[[10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
