# Simple Neural Network

- weight = 0.8

- input1 = [98.78, 19.25, 329, 900]

Write a Python function that takes any one input from the input1, and performs prediction by multiplying the input with weight. 

**Example:**

- Input: 19.25

- Output: 15.4

In [ ]:
#@title 
weight = 0.8
def simple_neural_network(input, weight):
    predict = input * weight
    return predict

input1 = [98.78, 19.25, 329, 900]
input = input1[1]
pred = simple_neural_network(input,weight)
print(pred)

15.4


In [ ]:
import numpy as np

a = np.array([0,1,2,3,4,5,6,7]) # vector
print(a)
print(a * 0.5) # multiply every number in vector "a" by 0.5

[0 1 2 3 4 5 6 7]
[0.  0.5 1.  1.5 2.  2.5 3.  3.5]


In [ ]:
b = np.array([8,9,10,11,12,13,14,15]) # vector
print(b)
print(b * 0.9) # multiply every number in vector "b" by 0.9

[ 8  9 10 11 12 13 14 15]
[ 7.2  8.1  9.   9.9 10.8 11.7 12.6 13.5]


In [ ]:
print(a * b) # multiplies elementwise between a and b (columns paired up)

[  0   9  20  33  48  65  84 105]


In [ ]:
c = np.array([[0,1,2,3,4,5,6,7],
              [8,9,10,11,12,13,14,15]])
print(c)
print('\n')
print(c * 2) # multiply by 2


[[ 0  1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14 15]]


[[ 0  2  4  6  8 10 12 14]
 [16 18 20 22 24 26 28 30]]


In [ ]:
d = np.zeros((2,8)) # (2x8 matrix of zeros)
print(d)

[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]


In [ ]:
e = np.random.rand(2,5) # random 2x8
print(e)

[[0.26129267 0.33614427 0.51522654 0.91134608 0.39411007]
 [0.66723525 0.20710495 0.07094916 0.64061263 0.85299251]]


In [ ]:
a = np.zeros((2,5)) # matrix with 2 rows and 5 columns
b = np.zeros((5,6)) # matrix with 5 rows and 6 columns

c = a.dot(b)
print(c.shape)

(2, 6)


In [ ]:
e = np.zeros((3,2)) # matrix with 3 rows and 2 columns
f = np.zeros((2,4)) # matrix with 2 row & 4 columns

g = e.dot(f)
print(g.shape)

(3, 4)


In [ ]:
h = np.zeros((7,9)).T # matrix with 9 rows and 7 columns
i = np.zeros((7,5)) # matrix with 7 rows & 5 columns

j = h.dot(i)
print(j.shape) 

(9, 5)


In [ ]:
h = np.zeros((5,9)) # matrix with 5 rows and 9 columns
i = np.zeros((7,3)) # matrix with 7 rows & 3 columns
j = h.dot(i)
print(j.shape) # we get an error

# Simple Neural Network using Multiple Inputs

The neural networks takes:

- 4 inputs

The neural network performs prediction by multiplying inputs with weights.

**Parameters**

Weight values:
- weight = [0.5, 0.6, 0, -0.9]

Four input values:
- input1 = [88.50, 9.5, 9.9, 9.0]
- input2 = [72.95, 0.8, 0.8, 0.9]
- input3 = [18.25, 32.36, 9.56, 1.45]
- input4 = [0.29, 0.70, 0.77, 1.7]

**Output = 87.759**

In [ ]:
#@title 
import numpy as np

weight = np.array([0.5, 0.6, 0, -0.9])


def simple_neural_network(input, weight):
    predict = input.dot(weight)
    return predict
    
input1 = np.array([88.50, 9.5, 9.9, 9.0])
input2 = np.array([72.95, 0.8, 0.8, 0.9])
input3 = np.array([18.25, 32.36, 9.56, 1.45])
input4 = np.array([0.29, 0.70, 0.77, 1.7])

input = np.array([input1[0],input2[0],input3[0],input4[0]])
pred = simple_neural_network(input,weight)

print(pred)

87.759


In [ ]:
import numpy as np

weight = .3
input = .8
ground_truth_prediction = 0.35

neural_network_prediction_ = input * weight

square_error = (neural_network_prediction_ - ground_truth_prediction) ** 2




In [ ]:
import numpy as np

weight = 0.3

def 